version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_local
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=quiz-app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
